// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZcYbNZ5tTYt8CHxqHrQXx3awEtCcVPGw',
    appId: '1:791268615472:web:d4c5fbd542cc081015d4f5',
    messagingSenderId: '791268615472',
    projectId: 'eato-delivery-partner',
    authDomain: 'eato-delivery-partner.firebaseapp.com',
    storageBucket: 'eato-delivery-partner.firebasestorage.app',
    measurementId: 'G-055BDHRSQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc9kt0yKhQ_8vSiadKZvddZhVOjoQjv7I',
    appId: '1:791268615472:android:7450364ec97a7b1015d4f5',
    messagingSenderId: '791268615472',
    projectId: 'eato-delivery-partner',
    storageBucket: 'eato-delivery-partner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3sSAQeaZcyrG6chiE4rODlYFClHQUpEo',
    appId: '1:791268615472:ios:e8da447c4552b53a15d4f5',
    messagingSenderId: '791268615472',
    projectId: 'eato-delivery-partner',
    storageBucket: 'eato-delivery-partner.firebasestorage.app',
    iosBundleId: 'com.example.eatoDeliveryPartner.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3sSAQeaZcyrG6chiE4rODlYFClHQUpEo',
    appId: '1:791268615472:ios:939d654420eb64d715d4f5',
    messagingSenderId: '791268615472',
    projectId: 'eato-delivery-partner',
    storageBucket: 'eato-delivery-partner.firebasestorage.app',
    iosBundleId: 'com.example.eatoDeliveryPartner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZcYbNZ5tTYt8CHxqHrQXx3awEtCcVPGw',
    appId: '1:791268615472:web:0cd2df79d7c1500c15d4f5',
    messagingSenderId: '791268615472',
    projectId: 'eato-delivery-partner',
    authDomain: 'eato-delivery-partner.firebaseapp.com',
    storageBucket: 'eato-delivery-partner.firebasestorage.app',
    measurementId: 'G-FLT71XXBBP',
  );
}
