// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyButrWi1PeULfdOZcT55j-9YmX4Y8H7MmQ',
    appId: '1:846077598972:web:300d54429a0082bbc94b79',
    messagingSenderId: '846077598972',
    projectId: 'localbasketpartner-ebda4',
    authDomain: 'localbasketpartner-ebda4.firebaseapp.com',
    storageBucket: 'localbasketpartner-ebda4.firebasestorage.app',
    measurementId: 'G-5SX7C3E5QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWfqUFbHRGL4FsxjDkN_RsExVlcRmbIjc',
    appId: '1:846077598972:android:b5bae2e0da7454c9c94b79',
    messagingSenderId: '846077598972',
    projectId: 'localbasketpartner-ebda4',
    storageBucket: 'localbasketpartner-ebda4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6FoUmEp_-TskqLIVbQfqoQN8E5NXppH8',
    appId: '1:846077598972:ios:b6e3d9169419310bc94b79',
    messagingSenderId: '846077598972',
    projectId: 'localbasketpartner-ebda4',
    storageBucket: 'localbasketpartner-ebda4.firebasestorage.app',
    iosBundleId: 'com.localbasket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6FoUmEp_-TskqLIVbQfqoQN8E5NXppH8',
    appId: '1:846077598972:ios:31a6f36c345c9312c94b79',
    messagingSenderId: '846077598972',
    projectId: 'localbasketpartner-ebda4',
    storageBucket: 'localbasketpartner-ebda4.firebasestorage.app',
    iosBundleId: 'com.example.localbasketDeliveryPartner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyButrWi1PeULfdOZcT55j-9YmX4Y8H7MmQ',
    appId: '1:846077598972:web:d5650f1f615a9a85c94b79',
    messagingSenderId: '846077598972',
    projectId: 'localbasketpartner-ebda4',
    authDomain: 'localbasketpartner-ebda4.firebaseapp.com',
    storageBucket: 'localbasketpartner-ebda4.firebasestorage.app',
    measurementId: 'G-1C2JDRXQGB',
  );
}
